- name: Deploy Scientific Calculator using Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Remove conflicting packages (if needed)
      apt:
        name: containerd.io
        state: absent
      ignore_errors: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the latest Docker image
      command: docker pull yanky1903/scientific-calculator:latest

    - name: Stop and remove old container if exists
      docker_container:
        name: scientific-calculator
        state: absent

    - name: Run the Docker container
      command: docker run -d --name scientific-calculator -p 8080:8080 yanky1903/scientific-calculator:latest
